server:
  port: 80

spring:
  jpa:
    hibernate:
      ddl-auto: update

  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssm_db
      username: root
      password: zl0539zl

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto